# Generated by Django 5.2.6 on 2025-09-30 14:23

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, max_length=500)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['ordem', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('reitor', 'Reitor'), ('vice_reitor', 'Vice-Reitor'), ('diretor', 'Diretor de Faculdade'), ('coordenador', 'Coordenador de Curso'), ('professor', 'Professor'), ('administrativo', 'Administrativo')], max_length=20)),
                ('nivel_hierarquico', models.IntegerField(default=10, help_text='1=Reitor, 2=Vice-Reitor, etc')),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nivel_hierarquico', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_universidade', models.CharField(default='URNM - Universidade', max_length=200)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='configuracao/')),
                ('cor_primaria', models.CharField(default='#90EE90', help_text='Cor em hexadecimal (verde bebê)', max_length=7)),
                ('cor_secundaria', models.CharField(default='#FFD700', help_text='Cor em hexadecimal (amarelo)', max_length=7)),
                ('link_siga', models.URLField(blank=True, help_text='Link para o sistema SIGA', max_length=500)),
                ('sobre_universidade', ckeditor.fields.RichTextField(blank=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('endereco', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=10)),
                ('descricao', ckeditor.fields.RichTextField(blank=True)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='faculdades/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('endereco', models.TextField(blank=True)),
                ('site_externo', models.URLField(blank=True, help_text='Link para site externo da faculdade', max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Faculdade',
                'verbose_name_plural': 'Faculdades',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', ckeditor.fields.RichTextField(blank=True)),
                ('tipo', models.CharField(choices=[('inicio_aulas', 'Início das Aulas'), ('fim_aulas', 'Fim das Aulas'), ('exames', 'Período de Exames'), ('matriculas', 'Matrículas'), ('ferias', 'Férias'), ('outro', 'Outro Evento')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ano_letivo', models.IntegerField()),
                ('semestre', models.IntegerField(blank=True, choices=[(1, '1º Semestre'), (2, '2º Semestre')], null=True)),
                ('publicado', models.BooleanField(default=True)),
                ('faculdade', models.ForeignKey(blank=True, help_text='Evento específico de uma faculdade', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faculdade')),
            ],
            options={
                'verbose_name': 'Evento Acadêmico',
                'verbose_name_plural': 'Eventos Acadêmicos',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('licenciatura', 'Licenciatura'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], default='licenciatura', max_length=20)),
                ('descricao', ckeditor.fields.RichTextField(blank=True)),
                ('duracao_anos', models.IntegerField(default=4, help_text='Duração em anos')),
                ('vagas', models.IntegerField(default=30)),
                ('objetivos', ckeditor.fields.RichTextField(blank=True)),
                ('perfil_profissional', ckeditor.fields.RichTextField(blank=True, help_text='Perfil do profissional formado')),
                ('requisitos_ingresso', ckeditor.fields.RichTextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('faculdade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.faculdade')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['faculdade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('biografia', ckeditor.fields.RichTextField(blank=True)),
                ('formacao', models.TextField(blank=True, help_text='Formação acadêmica')),
                ('especializacao', models.TextField(blank=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem_exibicao', models.IntegerField(default=0)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cargo')),
                ('faculdade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculdade')),
                ('superior_hierarquico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['cargo__nivel_hierarquico', 'ordem_exibicao', 'nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('obrigatoria', 'Obrigatória'), ('optativa', 'Optativa'), ('eletiva', 'Eletiva')], default='obrigatoria', max_length=20)),
                ('ano', models.IntegerField(help_text='Ano do curso (1, 2, 3, 4)')),
                ('semestre', models.IntegerField(help_text='Semestre (1 ou 2)')),
                ('carga_horaria', models.IntegerField(help_text='Carga horária total')),
                ('creditos', models.IntegerField(default=3)),
                ('ementa', ckeditor.fields.RichTextField(blank=True)),
                ('objetivos', ckeditor.fields.RichTextField(blank=True)),
                ('bibliografia', ckeditor.fields.RichTextField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.curso')),
                ('pre_requisitos', models.ManyToManyField(blank=True, related_name='dependentes', to='core.disciplina')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas_lecionadas', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['curso', 'ano', 'semestre', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_coordenados', to='core.funcionario'),
        ),
        migrations.CreateModel(
            name='NivelAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('administrador', 'Administrador'), ('gestor', 'Gestor'), ('professor', 'Professor')], default='professor', max_length=20)),
                ('funcionario', models.OneToOneField(blank=True, help_text='Vincular a um funcionário', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.funcionario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nível de Acesso',
                'verbose_name_plural': 'Níveis de Acesso',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('resumo', models.TextField(max_length=500)),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('imagem_destaque', models.ImageField(upload_to='noticias/')),
                ('destaque', models.BooleanField(default=False, help_text='Aparecer na área de destaque')),
                ('publicada', models.BooleanField(default=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('faculdade', models.ForeignKey(blank=True, help_text='Notícia específica de uma faculdade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faculdade')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
