# Generated by Django 5.2.6 on 2025-09-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='cor_primaria',
            field=models.CharField(default='#003366', help_text='Cor primária em hexadecimal (Navy Blue)', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='cor_secundaria',
            field=models.CharField(default='#C69214', help_text='Cor secundária em hexadecimal (Gold)', max_length=7),
        ),
    ]
